version: '3.8'

services:
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0'
    volumes:
      - .:/app
    networks:
      - backend
    expose:
      - 8000
    environment:
      - DATABASE_URL=postgresql://fastapi_traefik:fastapi_traefik@db:5432/fastapi_traefik
      - TESTING=0
      - SMTP_HOST= ${SMTP_HOST}
      - SMTP_PORT= ${SMTP_PORT}
      - SMTP_USERNAME= ${SMTP_USERNAME}
      - SMTP_PASSWORD= ${SMTP_PASSWORD}
      - EMAIL_FROM_NAME= ${EMAIL_FROM_NAME}
      - EMAIL_FROM_ADDRESS= ${EMAIL_FROM_ADDRESS}
      - API_URL = ${API_URL}

    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`${API_URL}`)"
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
    networks:
      - backend
  traefik:
    image: traefik:v2.9.6
    ports:
      - 8008:80
      - 8081:8080
    networks:
      - backend
    volumes:
      - "./traefik.dev.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  adminer:
    image: adminer
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres_server
    depends_on:
      - db
    links:
      - db
    networks:
      - backend

networks:
  backend:
    name: connect
volumes:
  postgres_data:
